export interface Product {
  slug: string;
  name: string;
  brand: string;
  brandSlug: string;
  price: number;
  priceUnit: string;
  installType: "paste-the-wall" | "peel-and-stick" | "both";
  imageUrl: string;
  images: string[];
  isNew?: boolean;
  isBestseller?: boolean;
  rating: number;
  reviewCount: number;
  description: string;
  details: {
    rollWidth: string;
    rollLength: string;
    patternRepeat: string;
    match: string;
    material: string;
    finish: string;
    origin: string;
  };
  tags: string[];
  relatedSlugs: string[];
}

export const PRODUCTS: Product[] = [
  {
    slug: "verdant-canopy",
    name: "Verdant Canopy",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 74,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    ],
    isBestseller: true,
    rating: 5,
    reviewCount: 214,
    description: "An expansive botanical mural that transforms any wall into a lush, verdant canopy. Sweeping tropical leaves in deep forest greens create a sense of depth and drama, bringing the outside world indoors with breathtaking effect. Printed to order on eco-certified substrate by Rebel Walls, Sweden's most celebrated mural house.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "64cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "Sweden",
    },
    tags: ["Botanical", "Paste-the-Wall", "Eco-certified", "Bestseller", "Mural"],
    relatedSlugs: ["midnight-garden", "emerald-conservatory"],
  },
  {
    slug: "hex-noir",
    name: "Hex Noir",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 58,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    isNew: true,
    rating: 5,
    reviewCount: 87,
    description: "A bold geometric statement in deep noir tones. Interlocking hexagonal forms create a hypnotic, dimensional surface that commands attention without overwhelming a space. Perfect for feature walls in home offices, hallways, and dining rooms. Available as peel-and-stick for renter-friendly installation.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "32cm half drop",
      match: "Half drop",
      material: "Vinyl-coated non-woven",
      finish: "Satin",
      origin: "United Kingdom",
    },
    tags: ["Geometric", "Peel & Stick", "Bold", "New", "Renter-friendly"],
    relatedSlugs: ["midnight-garden", "verdant-canopy"],
  },
  {
    slug: "midnight-garden",
    name: "Midnight Garden",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 84,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    isBestseller: true,
    rating: 5,
    reviewCount: 163,
    description: "A dark, moody garden scene rendered in the deep hours before dawn. Delicate botanicals emerge from an inky background in a palette of midnight blues and forest greens. This is wallpaper for those who understand that the most beautiful rooms are the ones that make you feel something.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "53cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["verdant-canopy", "hex-noir"],
  },
  {
    slug: "emerald-conservatory",
    name: "Emerald Conservatory",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 62,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    ],
    isNew: true,
    rating: 4,
    reviewCount: 52,
    description: "Step into the golden age of the Victorian conservatory. Lush emerald fronds and botanical specimens rendered in jewel-toned greens on a warm cream ground. Tempaper's signature self-adhesive formula means this luxury look installs in hours and removes cleanly — ideal for rental properties and temporary transformations.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "48cm half drop",
      match: "Half drop",
      material: "Self-adhesive vinyl",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Botanical", "Peel & Stick", "New", "Removable", "Victorian"],
    relatedSlugs: ["verdant-canopy", "midnight-garden"],
  },
  {
    slug: "papilio-botanical",
    name: "Papilio Botanical",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 92,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    ],
    rating: 5,
    reviewCount: 341,
    description: "A Sanderson archive original, reimagined for contemporary interiors. Delicate butterfly and botanical specimens rendered in the brand's signature layered print technique, with a depth and precision that rewards close inspection. Printed on heavyweight non-woven substrate in Sanderson's UK facility.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "53cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United Kingdom",
    },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Eco-certified"],
    relatedSlugs: ["verdant-canopy", "strawberry-thief"],
  },
  {
    slug: "strawberry-thief",
    name: "Strawberry Thief",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    isBestseller: true,
    rating: 5,
    reviewCount: 892,
    description: "William Morris's most celebrated design, first created in 1883 and as relevant today as it was in the Arts & Crafts era. Thrushes steal strawberries from the garden in this endlessly detailed pattern — a meditation on nature's abundance. Printed on archival-weight non-woven with water-based inks, faithful to the original block-print colourway.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "53cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United Kingdom",
    },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["papilio-botanical", "verdant-canopy"],
  },
  {
    slug: "magnolia-peel-stick",
    name: "Magnolia",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 64,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    ],
    isNew: true,
    rating: 5,
    reviewCount: 178,
    description: "Hygge & West's best-loved botanical, now available as peel-and-stick. Oversized magnolia blooms in the warmest blush-to-ivory gradient, rendered with the brand's signature illustrative quality. Removable without wall damage and repositionable during installation — ideal for renters who want to commit to beauty without committing permanently.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "48cm half drop",
      match: "Half drop",
      material: "Self-adhesive vinyl",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["emerald-conservatory", "garden-party"],
  },
  {
    slug: "momentum-grid",
    name: "Momentum Grid",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 78,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    rating: 4,
    reviewCount: 143,
    description: "A considered geometric from Harlequin's contemporary collection. Overlapping grids in a warm-neutral palette create a dimensional surface effect that reads as both architectural and quietly decorative. The muted colourway works in dining rooms, home offices, and any space that needs structure without statement.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "32cm half drop",
      match: "Half drop",
      material: "Non-woven substrate",
      finish: "Satin",
      origin: "United Kingdom",
    },
    tags: ["Geometric", "Paste-the-Wall"],
    relatedSlugs: ["hex-noir", "diamond-lattice"],
  },
  {
    slug: "diamond-lattice",
    name: "Diamond Lattice",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 66,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    ],
    rating: 4,
    reviewCount: 96,
    description: "A clean, architectural lattice in a soft contrast palette from York's modern collection. Diamond forms interlock across the surface in a pattern that suits both traditional and contemporary interiors. The non-woven substrate makes it straightforward to hang and to remove when you're ready to change direction.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "48cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Geometric", "Paste-the-Wall"],
    relatedSlugs: ["hex-noir", "momentum-grid"],
  },
  {
    slug: "woods-cole-son",
    name: "Woods",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    isBestseller: true,
    rating: 5,
    reviewCount: 476,
    description: "Cole & Son's iconic forest scene, first designed in the 1950s and now a design institution. A procession of birch trees in deepening hues — ivory, stone, and charcoal — creates a sense of walking into an endless winter woodland. The depth of the print, with its multi-layer overprinting, rewards every angle of light. A room hung with Woods is never the same room twice.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "64cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United Kingdom",
    },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["midnight-garden", "blackthorn"],
  },
  {
    slug: "blackthorn",
    name: "Blackthorn",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 56,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png",
    ],
    isNew: true,
    rating: 4,
    reviewCount: 61,
    description: "A moody, directional botanical in deep charcoal and forest green, designed for renters who want drama without commitment. Blackthorn branches weave across a near-black ground in a pattern that reads as bold from across the room and intricate up close. Peel-and-stick installation with zero wall damage on removal.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "48cm straight match",
      match: "Straight match",
      material: "Self-adhesive vinyl",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Dark & Moody", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["midnight-garden", "woods-cole-son"],
  },
  {
    slug: "archive-rose",
    name: "Archive Rose",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 96,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    rating: 5,
    reviewCount: 287,
    description: "Drawn from Sanderson's archive of florals dating back to the Victorian era, Archive Rose distils 150 years of English rose illustration into a single, quietly magnificent pattern. Blowsy blooms in dusty pink and ivory on a warm cream ground — the kind of wallpaper that makes a bedroom feel like it has always been there, even the first morning after hanging.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "53cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United Kingdom",
    },
    tags: ["Vintage Floral", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["garden-party", "strawberry-thief"],
  },
  {
    slug: "garden-party",
    name: "Garden Party",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 79,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    ],
    isNew: true,
    rating: 5,
    reviewCount: 134,
    description: "Anna Bond's illustrated florals have a warmth that photographs rarely capture — the hand-drawn quality, the slight imprecision that makes every bloom feel alive. Garden Party collects her most beloved flowers into an exuberant repeat that fills a room with colour and character. Available as peel-and-stick: as practical as it is beautiful.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "48cm half drop",
      match: "Half drop",
      material: "Self-adhesive vinyl",
      finish: "Matt",
      origin: "United States",
    },
    tags: ["Vintage Floral", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["archive-rose", "emerald-conservatory"],
  },
  {
    slug: "hummingbirds",
    name: "Hummingbirds",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 142,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png",
    ],
    rating: 5,
    reviewCount: 318,
    description: "Cole & Son's most enduring chinoiserie, first produced in 1950 and continuously in print since. Jewel-toned hummingbirds hover among magnolia blossoms and tropical foliage on a ground that ranges, across the colourway range, from ivory to sky to deepest navy. For those who understand that the best rooms are the ones that take a position.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "64cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Matt",
      origin: "United Kingdom",
    },
    tags: ["Chinoiserie", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["imperial-garden", "woods-cole-son"],
  },
  {
    slug: "imperial-garden",
    name: "Imperial Garden",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 88,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
    images: [
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png",
      "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png",
    ],
    rating: 4,
    reviewCount: 109,
    description: "A more accessible entry into chinoiserie from Graham & Brown's premium range. Pagodas, peonies, and exotic birds in cool jade and dusty rose on a warm cream ground. The chinoiserie tradition at a price point that doesn't require a second mortgage — for rooms that want the look without the full commitment.",
    details: {
      rollWidth: "52cm (20.5 in)",
      rollLength: "10m (32.8 ft)",
      patternRepeat: "53cm straight match",
      match: "Straight match",
      material: "Non-woven substrate",
      finish: "Satin",
      origin: "United Kingdom",
    },
    tags: ["Chinoiserie", "Paste-the-Wall"],
    relatedSlugs: ["hummingbirds", "hex-noir"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string): Product[] {
  const product = getProduct(slug);
  if (!product) return [];
  return product.relatedSlugs.map((s) => getProduct(s)).filter(Boolean) as Product[];
}
