export interface Product {
  slug: string;
  name: string;
  brand: string;
  brandSlug: string;
  price: number;
  priceUnit: string;
  installType: "paste-the-wall" | "peel-and-stick" | "both";
  imageUrl: string;
  images: string[];
  isNew?: boolean;
  isBestseller?: boolean;
  rating: number;
  reviewCount: number;
  description: string;
  details: {
    rollWidth: string;
    rollLength: string;
    patternRepeat: string;
    match: string;
    material: string;
    finish: string;
    origin: string;
  };
  tags: string[];
  relatedSlugs: string[];
}

// The four base images — assigned in a 4×5 Latin-square so no two
// adjacent cards in the grid share the same visual.
const IMG_A = "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160940_6effa5f0-e7e9-4fa1-8778-5effbd43b966.png";
const IMG_B = "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160651_6f151b60-e9e1-486d-8d44-e5fcd2348cd7.png";
const IMG_C = "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160653_f13ae913-090c-4797-ba0f-66a1694d1dc7.png";
const IMG_D = "https://d8j0ntlcm91z4.cloudfront.net/user_3EjidxRvAQx3MA2C4ZfgGXwr8Gw/hf_20260607_160943_0287b85a-2fd9-4ade-ae21-1c6bfd9fafbe.png";

// Grid order (4-col): row 1 A B C D | row 2 B C D A | row 3 C D A B |
//                     row 4 D A B C | row 5 A B C D … repeating
export const PRODUCTS: Product[] = [

  // ── Row 1 ──────────────────────────────────────────────────────
  {
    slug: "verdant-canopy",
    name: "Verdant Canopy",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 74,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B, IMG_C],
    isBestseller: true,
    rating: 5,
    reviewCount: 214,
    description: "An expansive botanical mural that transforms any wall into a lush, verdant canopy. Sweeping tropical leaves in deep forest greens create a sense of depth and drama, bringing the outside world indoors with breathtaking effect. Printed to order on eco-certified substrate by Rebel Walls, Sweden's most celebrated mural house.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Botanical", "Paste-the-Wall", "Eco-certified", "Bestseller", "Mural"],
    relatedSlugs: ["midnight-garden", "verdure"],
  },
  {
    slug: "emerald-conservatory",
    name: "Emerald Conservatory",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 62,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    isNew: true,
    rating: 4,
    reviewCount: 52,
    description: "Step into the golden age of the Victorian conservatory. Lush emerald fronds and botanical specimens rendered in jewel-toned greens on a warm cream ground. Tempaper's signature self-adhesive formula means this luxury look installs in hours and removes cleanly — ideal for rental properties and temporary transformations.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Botanical", "Peel & Stick", "New", "Removable", "Victorian"],
    relatedSlugs: ["verdant-canopy", "garden-party"],
  },
  {
    slug: "midnight-garden",
    name: "Midnight Garden",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 84,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    isBestseller: true,
    rating: 5,
    reviewCount: 163,
    description: "A dark, moody garden scene rendered in the deep hours before dawn. Delicate botanicals emerge from an inky background in a palette of midnight blues and forest greens. This is wallpaper for those who understand that the most beautiful rooms are the ones that make you feel something.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["woods-cole-son", "nocturne"],
  },
  {
    slug: "hex-noir",
    name: "Hex Noir",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 58,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    isNew: true,
    rating: 5,
    reviewCount: 87,
    description: "A bold geometric statement in deep noir tones. Interlocking hexagonal forms create a hypnotic, dimensional surface that commands attention without overwhelming a space. Perfect for feature walls in home offices, hallways, and dining rooms. Available as peel-and-stick for renter-friendly installation.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Vinyl-coated non-woven", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Peel & Stick", "Bold", "New", "Renter-friendly"],
    relatedSlugs: ["momentum-grid", "art-deco-soleil"],
  },

  // ── Row 2 ──────────────────────────────────────────────────────
  {
    slug: "archive-rose",
    name: "Archive Rose",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 96,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 287,
    description: "Drawn from Sanderson's archive of florals dating back to the Victorian era, Archive Rose distils 150 years of English rose illustration into a single, quietly magnificent pattern. Blowsy blooms in dusty pink and ivory on a warm cream ground — the kind of wallpaper that makes a bedroom feel like it has always been there.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Vintage Floral", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["meadow-bloom", "strawberry-thief"],
  },
  {
    slug: "woods-cole-son",
    name: "Woods",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    isBestseller: true,
    rating: 5,
    reviewCount: 476,
    description: "Cole & Son's iconic forest scene, first designed in the 1950s and now a design institution. A procession of birch trees in deepening hues — ivory, stone, and charcoal — creates a sense of walking into an endless winter woodland. The depth of the print, with its multi-layer overprinting, rewards every angle of light.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["midnight-garden", "velvet-forest"],
  },
  {
    slug: "momentum-grid",
    name: "Momentum Grid",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 78,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 4,
    reviewCount: 143,
    description: "A considered geometric from Harlequin's contemporary collection. Overlapping grids in a warm-neutral palette create a dimensional surface effect that reads as both architectural and quietly decorative. The muted colourway works in dining rooms, home offices, and any space that needs structure without statement.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Paste-the-Wall"],
    relatedSlugs: ["hex-noir", "diamond-lattice"],
  },
  {
    slug: "papilio-botanical",
    name: "Papilio Botanical",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 92,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 5,
    reviewCount: 341,
    description: "A Sanderson archive original, reimagined for contemporary interiors. Delicate butterfly and botanical specimens rendered in the brand's signature layered print technique, with a depth and precision that rewards close inspection. Printed on heavyweight non-woven substrate in Sanderson's UK facility.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Eco-certified"],
    relatedSlugs: ["verdant-canopy", "strawberry-thief"],
  },

  // ── Row 3 ──────────────────────────────────────────────────────
  {
    slug: "blackthorn",
    name: "Blackthorn",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 56,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    isNew: true,
    rating: 4,
    reviewCount: 61,
    description: "A moody, directional botanical in deep charcoal and forest green, designed for renters who want drama without commitment. Blackthorn branches weave across a near-black ground in a pattern that reads as bold from across the room and intricate up close. Peel-and-stick installation with zero wall damage on removal.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Dark & Moody", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["midnight-garden", "nocturne"],
  },
  {
    slug: "diamond-lattice",
    name: "Diamond Lattice",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 66,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 4,
    reviewCount: 96,
    description: "A clean, architectural lattice in a soft contrast palette from York's modern collection. Diamond forms interlock across the surface in a pattern that suits both traditional and contemporary interiors. The non-woven substrate makes it straightforward to hang and to remove when you're ready to change direction.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Geometric", "Paste-the-Wall"],
    relatedSlugs: ["hex-noir", "momentum-grid"],
  },
  {
    slug: "hummingbirds",
    name: "Hummingbirds",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 142,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 318,
    description: "Cole & Son's most enduring chinoiserie, first produced in 1950 and continuously in print since. Jewel-toned hummingbirds hover among magnolia blossoms and tropical foliage on a ground that ranges, across the colourway range, from ivory to sky to deepest navy. For those who understand that the best rooms are the ones that take a position.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Chinoiserie", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["imperial-garden", "woods-cole-son"],
  },
  {
    slug: "garden-party",
    name: "Garden Party",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 79,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    isNew: true,
    rating: 5,
    reviewCount: 134,
    description: "Anna Bond's illustrated florals have a warmth that photographs rarely capture — the hand-drawn quality, the slight imprecision that makes every bloom feel alive. Garden Party collects her most beloved flowers into an exuberant repeat that fills a room with colour and character. Available as peel-and-stick: as practical as it is beautiful.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Vintage Floral", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["archive-rose", "meadow-bloom"],
  },

  // ── Row 4 ──────────────────────────────────────────────────────
  {
    slug: "imperial-garden",
    name: "Imperial Garden",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 88,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 4,
    reviewCount: 109,
    description: "A more accessible entry into chinoiserie from Graham & Brown's premium range. Pagodas, peonies, and exotic birds in cool jade and dusty rose on a warm cream ground. The chinoiserie tradition at a price point that doesn't require a second mortgage — for rooms that want the look without the full commitment.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Chinoiserie", "Paste-the-Wall"],
    relatedSlugs: ["hummingbirds", "hex-noir"],
  },
  {
    slug: "magnolia-peel-stick",
    name: "Magnolia",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 64,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    isNew: true,
    rating: 5,
    reviewCount: 178,
    description: "Hygge & West's best-loved botanical, now available as peel-and-stick. Oversized magnolia blooms in the warmest blush-to-ivory gradient, rendered with the brand's signature illustrative quality. Removable without wall damage and repositionable during installation — ideal for renters who want to commit to beauty without committing permanently.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["emerald-conservatory", "garden-party"],
  },
  {
    slug: "strawberry-thief",
    name: "Strawberry Thief",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    isBestseller: true,
    rating: 5,
    reviewCount: 892,
    description: "William Morris's most celebrated design, first created in 1883 and as relevant today as it was in the Arts & Crafts era. Thrushes steal strawberries from the garden in this endlessly detailed pattern — a meditation on nature's abundance. Printed on archival-weight non-woven with water-based inks, faithful to the original block-print colourway.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["papilio-botanical", "archive-rose"],
  },
  {
    slug: "nocturne",
    name: "Nocturne",
    brand: "Timorous Beasties",
    brandSlug: "timorous-beasties",
    price: 134,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    isNew: true,
    rating: 5,
    reviewCount: 97,
    description: "Glasgow's most subversive wallpaper studio applies its darkly poetic sensibility to the nocturnal garden. Moon-flowers, midnight foliage, and moths on a near-black ground — haunting, precise, and entirely unlike anything else in our collection. Timorous Beasties has been making wallpaper that asks uncomfortable questions of comfort since 1990.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "New", "Heritage"],
    relatedSlugs: ["midnight-garden", "velvet-forest"],
  },

  // ── Row 5 ──────────────────────────────────────────────────────
  {
    slug: "verdure",
    name: "Verdure",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 118,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 5,
    reviewCount: 189,
    description: "A celebration of the medieval verdure tapestry tradition, reimagined for contemporary walls. Dense overlapping foliage in a richly layered palette — from sage and moss through to deepest woodland green — draws on centuries of European botanical artistry. Printed on heavyweight non-woven in Osborne & Little's UK studio.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["verdant-canopy", "papilio-botanical"],
  },
  {
    slug: "meadow-bloom",
    name: "Meadow Bloom",
    brand: "House of Hackney",
    brandSlug: "house-of-hackney",
    price: 112,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 143,
    description: "House of Hackney's signature maximalism applied to the English country meadow at full bloom. Oversized foxgloves, wildflowers, and grasses spill across the surface in a palette that is simultaneously bold and deeply British. The founders' belief — that decorating bravely is an act of self-expression — is everywhere in this design.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Vintage Floral", "Botanical", "Paste-the-Wall", "Maximalist"],
    relatedSlugs: ["archive-rose", "garden-party"],
  },
  {
    slug: "velvet-forest",
    name: "Velvet Forest",
    brand: "de Gournay",
    brandSlug: "de-gournay",
    price: 198,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    isBestseller: true,
    rating: 5,
    reviewCount: 74,
    description: "de Gournay is the closest wallpaper has come to couture — every panel hand-painted in their London studio by craftspeople who train for years before working on client commissions. Velvet Forest brings that extraordinary human effort to an atmospheric woodland scene: the deepest shadows, the most considered composition, layers of colour that no digital print can replicate.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["woods-cole-son", "nocturne"],
  },
  {
    slug: "art-deco-soleil",
    name: "Art Deco Soleil",
    brand: "Fromental",
    brandSlug: "fromental",
    price: 168,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 5,
    reviewCount: 58,
    description: "Fromental's hand-embroidered wallcoverings are without parallel — each panel taking weeks of studio time to complete. Art Deco Soleil interprets the optimistic geometry of the 1920s in a rich, layered surface that rewards sustained attention. Available as a precision screen print or, for those who want the full story, as full bespoke embroidery — an heirloom rather than a decoration.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Art Deco", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["momentum-grid", "diamond-lattice"],
  },

  // ── Row 6 ──────────────────────────────────────────────────────
  {
    slug: "jungle-reverie",
    name: "Jungle Reverie",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 79,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    isNew: true,
    rating: 5,
    reviewCount: 42,
    description: "A sweep of tropical jungle life rendered as an immersive full-height mural. Exotic birds, oversized philodendron leaves, and creeping vines form a wall-to-wall scene that transports any room to the equatorial jungle at dawn. Printed on Rebel Walls' premium eco-certified non-woven in Stockholm.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Botanical", "Paste-the-Wall", "Mural", "New"],
    relatedSlugs: ["verdant-canopy", "palm-paradise"],
  },
  {
    slug: "chevron-slate",
    name: "Chevron Slate",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 62,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    rating: 4,
    reviewCount: 118,
    description: "A confident chevron in warm slates and stone neutrals. Directional and graphic without being loud, this geometric suits everything from home offices to hallways and pairs particularly well with warm timber and brushed brass. Non-woven substrate with a subtle satin finish.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Vinyl-coated non-woven", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Paste-the-Wall", "Abstract"],
    relatedSlugs: ["hex-noir", "momentum-grid"],
  },
  {
    slug: "terracotta-wave",
    name: "Terracotta Wave",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 78,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    isNew: true,
    rating: 5,
    reviewCount: 67,
    description: "A fluid, organic wave pattern in terracotta, blush, and warm sand — the earthy palette of the American Southwest by way of Brooklyn. Chasing Paper's peel-and-stick formula makes this a favourite for renters who want a boho statement without a permanent commitment.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Boho", "Abstract", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["desert-bloom", "sage-scatter"],
  },
  {
    slug: "coral-reef",
    name: "Coral Reef",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 66,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 4,
    reviewCount: 83,
    description: "An underwater world rendered in warm coral, sand, and ocean blue — Tempaper's take on the coastal aesthetic, precise enough to feel designed, playful enough for a nursery or beach house bathroom. Peel-and-stick application with clean-release adhesive.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Botanical", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["lily-pad-pond", "shell-bisque"],
  },

  // ── Row 7 ──────────────────────────────────────────────────────
  {
    slug: "peony-garden",
    name: "Peony Garden",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    isBestseller: true,
    rating: 5,
    reviewCount: 204,
    description: "Sanderson's lush peony garden in full midsummer bloom, drawn from the brand's Victorian archive and reprinted on heavyweight non-woven. Oversized blooms in blush, coral, and ivory cluster across a warm cream ground — quintessential English maximalism at its most wearable.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Vintage Floral", "Grandmillennial", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["archive-rose", "bramble-rose"],
  },
  {
    slug: "willow-bough",
    name: "Willow Bough",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 122,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 5,
    reviewCount: 412,
    description: "William Morris's Willow Bough, first designed in 1887, captures the weeping willow's gentle weight with a precision that has not dated in over 130 years. The pattern tiles with the seamlessness of its original woodblock print, carrying the same rhythmic movement that makes Morris's work instantly recognisable.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["strawberry-thief", "acanthus-scroll"],
  },
  {
    slug: "fjord-fog",
    name: "Fjord Fog",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 88,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 4,
    reviewCount: 76,
    description: "A soft, atmospheric abstract inspired by the Scandinavian coastline in morning mist. Loose watercolour washes in pale grey, blue, and cloud-white create a calming, meditative surface ideal for bedrooms and reading rooms where quiet is the point.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Abstract", "Coastal", "Paste-the-Wall"],
    relatedSlugs: ["nordic-frost", "blue-linen"],
  },
  {
    slug: "aurora-wave",
    name: "Aurora Wave",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 94,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    isNew: true,
    rating: 5,
    reviewCount: 54,
    description: "Harlequin captures the northern lights in a bold, fluid abstract. Sweeping bands of colour — deep aurora green, lavender, and midnight — undulate across the surface in a pattern that fills a room with movement and atmosphere without committing to a figurative image.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Abstract", "Paste-the-Wall", "New"],
    relatedSlugs: ["fjord-fog", "tangent-stripe"],
  },

  // ── Row 8 ──────────────────────────────────────────────────────
  {
    slug: "coastal-rope",
    name: "Coastal Rope",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 72,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 4,
    reviewCount: 91,
    description: "A nautical rope lattice in navy, natural, and cream — York's measured take on coastal decor. The geometric structure keeps the design from tipping into kitsch, while the colourway grounds it firmly in the coastal tradition. Suitable for hallways, bathrooms, and dining rooms.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Geometric", "Paste-the-Wall"],
    relatedSlugs: ["shell-bisque", "blue-linen"],
  },
  {
    slug: "king-protea",
    name: "King Protea",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 158,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 147,
    description: "Cole & Son's botanical archive turns to the South African protea — king of the fynbos — in this bold, characterful design. Sculptural blooms and architectural leaves in a palette of rust, dusty pink, and khaki green: the kind of design that makes a room feel like a collector lives there.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["hummingbirds", "flamingo-pink"],
  },
  {
    slug: "coastal-stripe",
    name: "Coastal Stripe",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 48,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    rating: 4,
    reviewCount: 157,
    description: "A classic wide stripe in navy and warm white, sharp enough to read as considered and accessible enough for any coastal or transitional interior. Brewster's non-woven substrate makes hanging straightforward and removal clean — a no-regrets choice for the first-time paperhanger.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "16cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Geometric", "Paste-the-Wall"],
    relatedSlugs: ["coastal-rope", "stripe-dusk"],
  },
  {
    slug: "wildflower-field",
    name: "Wildflower Field",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 92,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    isNew: true,
    rating: 5,
    reviewCount: 88,
    description: "Anna Bond's illustrated meadow — daisies, cornflowers, poppies, and ox-eye daisies rendered in her unmistakable hand. The field sprawls in all directions with the controlled chaos of a real meadow in July. Available as peel-and-stick for renters who want the most optimistic room in the building.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Vintage Floral", "Cottage Core", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["garden-party", "daisy-meadow"],
  },

  // ── Row 9 ──────────────────────────────────────────────────────
  {
    slug: "folly-brook",
    name: "Folly Brook",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 124,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 5,
    reviewCount: 93,
    description: "Osborne & Little's romantic countryside scene: a babbling brook winds between willows and meadow grasses in a soft, layered palette of sage, stone, and pale blue. A wallpaper that makes a room feel like a painting — pastoral, considered, and quietly optimistic.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Cottage Core", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["verdure", "jacobean-tree"],
  },
  {
    slug: "limerence",
    name: "Limerence",
    brand: "House of Hackney",
    brandSlug: "house-of-hackney",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    isBestseller: true,
    rating: 5,
    reviewCount: 186,
    description: "House of Hackney's most overwhelmingly beautiful design — oversized tropicals, exotic birds, and cascading blooms in the most saturated palette in the collection. The founders describe limerence as 'the involuntary state of mind that results from a romantic attraction.' Their wallpaper of the same name is appropriately overwhelming.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Maximalist", "Botanical", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["palmeral", "wilderness-emerald"],
  },
  {
    slug: "thistle-dark",
    name: "Thistle Dark",
    brand: "Timorous Beasties",
    brandSlug: "timorous-beasties",
    price: 142,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    rating: 5,
    reviewCount: 79,
    description: "Scotland's national emblem on a near-black ground — Timorous Beasties at their most characteristically Scottish. The thistle's purple and silver are rendered with the same irreverent precision the Glasgow studio has brought to every design since 1990, transforming patriotism into something genuinely beautiful.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["nocturne", "moth-nocturne"],
  },
  {
    slug: "shou-lao",
    name: "Shou Lao",
    brand: "de Gournay",
    brandSlug: "de-gournay",
    price: 215,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 5,
    reviewCount: 41,
    description: "de Gournay's interpretation of the Chinese deity of longevity, hand-painted in their London studio on tea paper ground. Figures move through a celestial landscape of pine, peach blossom, and cloud formations in a design that rewards extended contemplation and improves with every viewing.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Hand-painted silk", finish: "Matt", origin: "United Kingdom" },
    tags: ["Chinoiserie", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["velvet-forest", "moonlit-garden"],
  },

  // ── Row 10 ──────────────────────────────────────────────────────
  {
    slug: "chevron-gold",
    name: "Chevron Gold",
    brand: "Fromental",
    brandSlug: "fromental",
    price: 178,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    rating: 5,
    reviewCount: 36,
    description: "Fromental's Art Deco chevron in 22-carat gold leaf on a rich ground of deep burgundy and noir. The geometry of the 1920s made palpable — a design that fills a room with the glamour of the Chrysler Building's lobby. Available in bespoke colourways on request.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Metallic", origin: "United Kingdom" },
    tags: ["Art Deco", "Geometric", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["art-deco-soleil", "deco-lattice"],
  },
  {
    slug: "savanna-dusk",
    name: "Savanna Dusk",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 84,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 4,
    reviewCount: 63,
    description: "The East African savanna at the golden hour — acacia silhouettes, dusty ochre, and the long shadows of late afternoon. Rebel Walls' mural specialists have created a scene that brings the world's most cinematic landscape into the dining room or bedroom with their characteristic large-format precision.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Botanical", "Paste-the-Wall", "Mural"],
    relatedSlugs: ["verdant-canopy", "arctic-grove"],
  },
  {
    slug: "arch-shadow",
    name: "Arch Shadow",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 64,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 4,
    reviewCount: 105,
    description: "A sophisticated architectural repeat — rounded arches casting deep shadows on warm stone — drawn from Graham & Brown's modern classics range. The pattern balances graphic ambition with a palette restrained enough to work across a wide range of interior styles.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Abstract", "Geometric", "Paste-the-Wall"],
    relatedSlugs: ["chevron-slate", "mosaic-blush"],
  },
  {
    slug: "desert-bloom",
    name: "Desert Bloom",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 82,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    isNew: true,
    rating: 5,
    reviewCount: 71,
    description: "Desert succulents and Southwest blooms rendered in warm terracotta and sage — the palette that defines modern boho interiors. Chasing Paper's peel-and-stick version makes this a zero-commitment path to the look, removable without residue and repositionable during installation.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Boho", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["terracotta-wave", "fern-frond"],
  },

  // ── Row 11 ──────────────────────────────────────────────────────
  {
    slug: "sunburst-retro",
    name: "Sunburst Retro",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 68,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    isNew: true,
    rating: 4,
    reviewCount: 49,
    description: "A sunburst pattern drawn from mid-century modern design — radiating lines and concentric arcs in warm mustard, burnt orange, and cream. Tempaper's self-adhesive formula makes it as easy to install as it is to admire, and as easy to remove when the decade changes.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Geometric", "Abstract", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["hex-noir", "indigo-lattice"],
  },
  {
    slug: "bluebell-wood",
    name: "Bluebell Wood",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 112,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 5,
    reviewCount: 176,
    description: "The English bluebell wood in full April bloom — a wash of blue-purple that drifts beneath canopied oaks. Sanderson's take on this quintessentially English scene is characteristic: precise botanical illustration, a palette that never strays into sweetness, and heavyweight non-woven substrate.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Cottage Core", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["archive-rose", "papilio-botanical"],
  },
  {
    slug: "chrysanthemum-blue",
    name: "Chrysanthemum Blue",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 223,
    description: "Morris & Co.'s chrysanthemum in indigo and cobalt — one of the firm's most accomplished colour studies. The flower's complex overlapping petals become almost abstract when repeated, moving between representation and geometry depending on where your eye falls.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["strawberry-thief", "golden-lily"],
  },
  {
    slug: "pine-needle",
    name: "Pine Needle",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 86,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    rating: 4,
    reviewCount: 94,
    description: "The Scandinavian pine forest distilled to its graphic essence — a single pine branch repeated in a clean, tonal pattern in shades of deep green and warm white. Hygge & West's botanical range offers the quieter, more restrained end of the nature-in-interiors spectrum.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Botanical", "Paste-the-Wall"],
    relatedSlugs: ["magnolia-peel-stick", "fjord-fog"],
  },

  // ── Row 12 ──────────────────────────────────────────────────────
  {
    slug: "geo-burst",
    name: "Geo Burst",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 98,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 4,
    reviewCount: 112,
    description: "Harlequin's most exuberant geometric — a starburst pattern that fills a wall with graphic energy. The design is crisp and confident, suited to feature walls in living rooms, dining rooms, and powder rooms where making a statement is exactly the brief.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Paste-the-Wall"],
    relatedSlugs: ["momentum-grid", "tangent-stripe"],
  },
  {
    slug: "blue-linen",
    name: "Blue Linen",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 68,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 4,
    reviewCount: 138,
    description: "A woven linen texture in soft chambray blue — the wallpaper equivalent of a favourite linen shirt. York's textured print convincingly replicates the warp and weft of natural fabric, lending walls a warmth and depth that flat paint never achieves.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "Free match", match: "Free match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Abstract", "Paste-the-Wall"],
    relatedSlugs: ["fjord-fog", "grasscloth-natural"],
  },
  {
    slug: "shiplap-white",
    name: "Shiplap White",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 42,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 4,
    reviewCount: 263,
    description: "Clean horizontal shiplap boards in bright white with subtle shadow — the wallpaper version of the most requested interior feature of the last decade. Brewster's affordable non-woven substrate installs easily and removes cleanly, ideal for renters and first-time paperhangers embracing the farmhouse aesthetic.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "16cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Cottage Core", "Paste-the-Wall"],
    relatedSlugs: ["daisy-meadow", "farmhouse-bloom"],
  },
  {
    slug: "strawberry-fields",
    name: "Strawberry Fields",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 88,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    rating: 5,
    reviewCount: 117,
    description: "Rifle Paper Co.'s illustrated strawberries tumble across a warm cream ground — a pattern that lands between cottage garden and country kitchen, charming enough for a child's room and considered enough for a dining room. Available as peel-and-stick for renters.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Vintage Floral", "Cottage Core", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["garden-party", "perennial-garden"],
  },

  // ── Row 13 ──────────────────────────────────────────────────────
  {
    slug: "sea-grass",
    name: "Sea Grass",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 84,
    description: "Osborne & Little captures the hypnotic movement of sea grass in shallow coastal water — sinuous vertical forms in warm greens and sandy gold. The design evokes the particular peace of coast-adjacent rooms: summer mornings, salt air, and bare feet on warm stone.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Coastal", "Botanical", "Paste-the-Wall"],
    relatedSlugs: ["folly-brook", "shell-bisque"],
  },
  {
    slug: "palmeral",
    name: "Palmeral",
    brand: "House of Hackney",
    brandSlug: "house-of-hackney",
    price: 132,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    isBestseller: true,
    rating: 5,
    reviewCount: 247,
    description: "House of Hackney's iconic palm-leaf print — the design that launched a thousand maximalist living rooms. Oversized fronds in the deepest emerald on a contrasting warm ground, layered with a confidence that only a brand who genuinely doesn't care what you think could achieve.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Maximalist", "Botanical", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["limerence", "wilderness-emerald"],
  },
  {
    slug: "glasgow-bird",
    name: "Glasgow Bird",
    brand: "Timorous Beasties",
    brandSlug: "timorous-beasties",
    price: 138,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 5,
    reviewCount: 68,
    description: "The European robin transformed by Timorous Beasties' darkly poetic lens — perched among thorned branches on a ground that suggests an overgrown Victorian garden after midnight. Precise, unsettling, and unmistakably from Glasgow.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["nocturne", "thistle-dark"],
  },
  {
    slug: "edo-birds",
    name: "Edo Birds",
    brand: "de Gournay",
    brandSlug: "de-gournay",
    price: 225,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 5,
    reviewCount: 38,
    description: "de Gournay's Edo collection brings the precision of Edo-period Japanese woodblock print to hand-painted wallpaper. Birds of paradise and Japanese crane move through a landscape of pine, cherry blossom, and mist on a ground of deep ocean blue — every panel a small painting.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Hand-painted silk", finish: "Matt", origin: "United Kingdom" },
    tags: ["Chinoiserie", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["shou-lao", "moonlit-garden"],
  },

  // ── Row 14 ──────────────────────────────────────────────────────
  {
    slug: "broadway-noir",
    name: "Broadway Noir",
    brand: "Fromental",
    brandSlug: "fromental",
    price: 182,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    rating: 5,
    reviewCount: 44,
    description: "Art Deco Broadway at midnight — Fromental's darkest design draws on the typography and geometry of 1930s New York in a rich, complex surface of charcoal, gold, and deep plum. The glamour of the pre-war city made material, for rooms that want to feel genuinely cinematic.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Art Deco", "Dark & Moody", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["art-deco-soleil", "chevron-gold"],
  },
  {
    slug: "palm-paradise",
    name: "Palm Paradise",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 82,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    rating: 5,
    reviewCount: 127,
    description: "A coastal palm grove rendered as an immersive mural — tall trunks, sweeping fronds, and the particular quality of light that filters through palm canopy at midday. Rebel Walls' large-format print quality means the detail in leaf shadow and trunk texture rewards close inspection.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Coastal", "Botanical", "Paste-the-Wall", "Mural"],
    relatedSlugs: ["jungle-reverie", "verdant-canopy"],
  },
  {
    slug: "mosaic-blush",
    name: "Mosaic Blush",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 58,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    isNew: true,
    rating: 4,
    reviewCount: 72,
    description: "A geometric mosaic in warm blush, terracotta, and ivory — Graham & Brown's most feminine design, drawing on the ancient art of tessellation. The repeat reads as abstract from a distance and reveals its mosaic structure as you approach.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Abstract", "Geometric", "Paste-the-Wall", "New"],
    relatedSlugs: ["arch-shadow", "linen-weave"],
  },
  {
    slug: "sunset-stripe",
    name: "Sunset Stripe",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 74,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 4,
    reviewCount: 96,
    description: "Bold horizontal stripes in the warm palette of a Pacific sunset — burnt orange, coral, dusty pink, and cream. Chasing Paper's wide-stripe format makes a room feel taller and the design considered rather than merely decorative. Available as peel-and-stick.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "16cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Boho", "Abstract", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["terracotta-wave", "stripe-dusk"],
  },

  // ── Row 15 ──────────────────────────────────────────────────────
  {
    slug: "grasscloth-natural",
    name: "Grasscloth Natural",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 72,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 5,
    reviewCount: 201,
    description: "Tempaper's high-fidelity grasscloth simulation — the warmth and texture of natural grasscloth on a peel-and-stick substrate that installs in hours and removes cleanly. The natural, irregular texture reads convincingly across every room it enters.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "Free match", match: "Free match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Abstract", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["blue-linen", "linen-weave"],
  },
  {
    slug: "honeysuckle-trellis",
    name: "Honeysuckle Trellis",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 115,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 5,
    reviewCount: 158,
    description: "Sanderson's honeysuckle climbing through a formal garden trellis — a design that distils centuries of English garden culture into a single, beautifully printed repeat. The scent may be absent but the mood of a summer garden at its peak is entirely present.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Vintage Floral", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["archive-rose", "peony-garden"],
  },
  {
    slug: "acanthus-scroll",
    name: "Acanthus Scroll",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 132,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    isBestseller: true,
    rating: 5,
    reviewCount: 534,
    description: "The acanthus leaf scroll — the oldest decorative motif in Western art — as only Morris & Co. can render it. Drawn from the firm's Arts & Crafts archive, this is the design that made William Morris's reputation for understanding the grammar of ornament.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Heritage", "Botanical", "Grandmillennial", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["strawberry-thief", "willow-bough"],
  },
  {
    slug: "noma-grid",
    name: "Noma Grid",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 84,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 4,
    reviewCount: 87,
    description: "A clean, architectural grid in warm white on off-white — the Scandinavian aesthetic reduced to its most essential geometry. Hygge & West's restrained approach to pattern is on full display: the design does everything it needs to without a single unnecessary element.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "16cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Geometric", "Abstract", "Paste-the-Wall"],
    relatedSlugs: ["momentum-grid", "fjord-fog"],
  },

  // ── Row 16 ──────────────────────────────────────────────────────
  {
    slug: "tropical-luxe",
    name: "Tropical Luxe",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 5,
    reviewCount: 134,
    description: "Harlequin's most glamorous botanical — oversized tropical leaves in deep emerald and midnight black on a gold-touched background. The design sits between botanical precision and pure luxury, suited to dining rooms and bedroom feature walls where drama is the entire brief.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Botanical", "Maximalist", "Paste-the-Wall"],
    relatedSlugs: ["limerence", "palmeral"],
  },
  {
    slug: "farmhouse-bloom",
    name: "Farmhouse Bloom",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 75,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 4,
    reviewCount: 172,
    description: "Wild garden flowers in a soft, faded palette on a warm cream ground — York's take on the English cottage garden via American farmhouse. The deliberately weathered quality of the print gives the design an antique depth that looks convincing on older walls.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Cottage Core", "Vintage Floral", "Paste-the-Wall"],
    relatedSlugs: ["daisy-meadow", "wildflower-field"],
  },
  {
    slug: "daisy-meadow",
    name: "Daisy Meadow",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 45,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    rating: 4,
    reviewCount: 198,
    description: "A cheerful, unpretentious meadow of daisies in white, yellow, and green on a clean white ground. Brewster makes the most accessible entry into the cottage core aesthetic — honest, warm, and straightforward. The non-woven substrate hangs and strips easily for the first-time paperhanger.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Cottage Core", "Vintage Floral", "Paste-the-Wall"],
    relatedSlugs: ["shiplap-white", "farmhouse-bloom"],
  },
  {
    slug: "bramble-rose",
    name: "Bramble Rose",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 95,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    rating: 5,
    reviewCount: 143,
    description: "Anna Bond's illustrated wild rose — thorned bramble stems, unfurling buds, and open blooms in dusty pink, sage, and ivory. The design has the quality of a hand-pressed botanical illustration elevated to wall scale, suited to bedrooms and dressing rooms.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Vintage Floral", "Botanical", "Paste-the-Wall"],
    relatedSlugs: ["garden-party", "peony-garden"],
  },

  // ── Row 17 ──────────────────────────────────────────────────────
  {
    slug: "peacock-manor",
    name: "Peacock Manor",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 138,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 5,
    reviewCount: 76,
    description: "Osborne & Little's interpretation of the Art Nouveau peacock — a tradition running from William Morris through to Erte. The bird's tail feathers spread across the wall in a pattern that is simultaneously historical and arresting, in a palette of deep teal, ochre, and gold.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Art Deco", "Dark & Moody", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["verdure", "regency-damask"],
  },
  {
    slug: "wilderness-emerald",
    name: "Wilderness Emerald",
    brand: "House of Hackney",
    brandSlug: "house-of-hackney",
    price: 138,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 162,
    description: "House of Hackney takes the dark botanical into its deepest territory — a dense, almost impenetrable jungle of foliage in every shade of green, from acid to near-black. The effect on a feature wall is like standing at the edge of a rainforest. For rooms that want to feel genuinely untamed.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Maximalist", "Dark & Moody", "Botanical", "Paste-the-Wall"],
    relatedSlugs: ["limerence", "palmeral"],
  },
  {
    slug: "lichen-stone",
    name: "Lichen Stone",
    brand: "Timorous Beasties",
    brandSlug: "timorous-beasties",
    price: 136,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    isNew: true,
    rating: 4,
    reviewCount: 52,
    description: "Lichen patterns on Scottish stone — the slow language of nature on rock rendered at wall scale. Timorous Beasties has taken the most patient and overlooked form of botanical life and given it the wall presence it has always deserved.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Abstract", "Dark & Moody", "Paste-the-Wall", "New"],
    relatedSlugs: ["nocturne", "thistle-dark"],
  },
  {
    slug: "moonlit-garden",
    name: "Moonlit Garden",
    brand: "de Gournay",
    brandSlug: "de-gournay",
    price: 228,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    rating: 5,
    reviewCount: 33,
    description: "de Gournay's night garden — hand-painted lunar flowers and phosphorescent foliage against a ground of midnight indigo. The studio's artists spend weeks on each panel, building up layers of colour and detail that capture the particular magic of a garden seen by moonlight.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Hand-painted silk", finish: "Matt", origin: "United Kingdom" },
    tags: ["Chinoiserie", "Dark & Moody", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["velvet-forest", "shou-lao"],
  },

  // ── Row 18 ──────────────────────────────────────────────────────
  {
    slug: "deco-lattice",
    name: "Deco Lattice",
    brand: "Fromental",
    brandSlug: "fromental",
    price: 172,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 47,
    description: "Fromental's Art Deco lattice — a precision geometry of interlocking diamonds and lines in a metallic gold-on-charcoal colourway. The studio's understanding of the 1920s goes beyond visual quotation into something that genuinely captures the era's relationship between luxury and geometry.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Metallic", origin: "United Kingdom" },
    tags: ["Art Deco", "Geometric", "Paste-the-Wall", "Heritage", "Luxury"],
    relatedSlugs: ["chevron-gold", "art-deco-soleil"],
  },
  {
    slug: "rainforest-floor",
    name: "Rainforest Floor",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 76,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 4,
    reviewCount: 88,
    description: "Rebel Walls goes vertical — the rainforest floor viewed from below, with canopy leaves reaching upward. Ferns, mosses, and exotic ground plants create an enveloping scene that transforms a room into something between a botanical garden and a tropical meditation space.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Botanical", "Paste-the-Wall", "Mural"],
    relatedSlugs: ["verdant-canopy", "jungle-reverie"],
  },
  {
    slug: "stripe-dusk",
    name: "Stripe Dusk",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 54,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 4,
    reviewCount: 129,
    description: "A wide, tonal stripe in the warm greys and dusty mauves of dusk — Graham & Brown's most minimal design, and one of the most versatile. The stripe reads as both textural and geometric, pairing with virtually any furniture style from Scandi to maximalist.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "16cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Geometric", "Abstract", "Paste-the-Wall"],
    relatedSlugs: ["chevron-slate", "linen-weave"],
  },
  {
    slug: "indigo-lattice",
    name: "Indigo Lattice",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 76,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 104,
    description: "A precise diamond lattice in deep indigo and white — the geometry of Japanese denim applied to wallpaper. Chasing Paper's peel-and-stick indigo lattice is a favourite for home offices and kitchen splashbacks among renters who want a polished look without permanent commitment.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Geometric", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["hex-noir", "sunburst-retro"],
  },

  // ── Row 19 ──────────────────────────────────────────────────────
  {
    slug: "lily-pad-pond",
    name: "Lily Pad Pond",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 68,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    rating: 4,
    reviewCount: 77,
    description: "Lily pads floating on still water — Tempaper's most painterly design, taking its cue from the Impressionist tradition and rendering it with digital precision. The soft blues, greens, and whites work in bathrooms, powder rooms, and any space that benefits from the calm of still water.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Botanical", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["coral-reef", "fern-frond"],
  },
  {
    slug: "etchings-seas",
    name: "Etchings & Seas",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 118,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 5,
    reviewCount: 92,
    description: "Sanderson's Etchings & Roses archive yields this coastal scene — boats on a choppy sea, rendered in the fine-line quality of Victorian copperplate etching on a warm cream ground. Heritage aesthetics applied to the seaside: for the coastal home that takes its decoration seriously.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Coastal", "Heritage", "Paste-the-Wall"],
    relatedSlugs: ["american-toile", "toile-countryside"],
  },
  {
    slug: "golden-lily",
    name: "Golden Lily",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 135,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 5,
    reviewCount: 318,
    description: "Morris & Co.'s Golden Lily: a pattern of interlocking lily blooms and leaves in ochre, gold, and deep forest green that has been in continuous production since the 1890s. The design's warm palette makes it unusually versatile across bedroom, living room, and dining room applications.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Heritage", "Botanical", "Vintage Floral", "Grandmillennial", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["strawberry-thief", "acanthus-scroll"],
  },
  {
    slug: "nordic-frost",
    name: "Nordic Frost",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 88,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    rating: 4,
    reviewCount: 61,
    description: "Hygge & West's abstract winter — a wash of watercolour whites and cool blues that evokes a Scandinavian morning after overnight snowfall. The palette is intentionally limited and the effect is one of complete calm, ideal for bedrooms and spaces designed for genuine rest.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Abstract", "Paste-the-Wall"],
    relatedSlugs: ["fjord-fog", "noma-grid"],
  },

  // ── Row 20 ──────────────────────────────────────────────────────
  {
    slug: "monstera-shadow",
    name: "Monstera Shadow",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 5,
    reviewCount: 119,
    description: "Harlequin's most considered dark botanical — a monstera design in deep charcoal and forest green on a near-black ground, where the shapes of the leaves are almost absorbed into the background before they emerge. Best seen in a room with good directional light.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall"],
    relatedSlugs: ["tropical-luxe", "nocturne"],
  },
  {
    slug: "american-toile",
    name: "American Toile",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 78,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 4,
    reviewCount: 137,
    description: "York's Americana version of the classic toile de Jouy — scenes of colonial American life rendered in traditional indigo monochrome on cream. Grandmillennial elegance with a distinctly American accent, for rooms that wear their history with confidence.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Grandmillennial", "Heritage", "Paste-the-Wall"],
    relatedSlugs: ["toile-countryside", "regency-damask"],
  },
  {
    slug: "boho-mudcloth",
    name: "Boho Mudcloth",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 52,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    isNew: true,
    rating: 4,
    reviewCount: 84,
    description: "A geometric pattern drawn from West African mudcloth textile tradition — angular, rhythmic forms in warm cream and deep charcoal that bring a global, bohemian intelligence to walls. Brewster's accessible price point makes this the most democratic route to the boho aesthetic.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Boho", "Geometric", "Paste-the-Wall", "New"],
    relatedSlugs: ["terracotta-wave", "loft-concrete"],
  },
  {
    slug: "canopy-illustrated",
    name: "Canopy Illustrated",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 92,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 5,
    reviewCount: 98,
    description: "Anna Bond's illustrated tree canopy — looking up through branches and leaves into a dappled sky. The design captures a specific memory: lying on your back in a garden in July, watching the light move through the leaves. As beautiful in a nursery as it is in a living room.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Botanical", "Paste-the-Wall"],
    relatedSlugs: ["wildflower-field", "perennial-garden"],
  },

  // ── Row 21 ──────────────────────────────────────────────────────
  {
    slug: "regency-damask",
    name: "Regency Damask",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 132,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_B],
    rating: 5,
    reviewCount: 111,
    description: "The damask — the most enduring pattern in European interiors — reinterpreted by Osborne & Little with a precision and restraint that brings it back from the edge of pastiche. In warm stone and ivory, this is the wallpaper equivalent of a perfectly tailored suit: formal but never stuffy.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Grandmillennial", "Heritage", "Paste-the-Wall"],
    relatedSlugs: ["american-toile", "jacobean-tree"],
  },
  {
    slug: "fruit-folly",
    name: "Fruit Folly",
    brand: "House of Hackney",
    brandSlug: "house-of-hackney",
    price: 136,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    isNew: true,
    rating: 5,
    reviewCount: 73,
    description: "House of Hackney's ode to the English kitchen garden — lemons, pomegranates, figs, and berries in the most exuberant, abundant arrangement. The design is maximalist but never chaotic, with a structure beneath the riot of colour and fruit that rewards careful looking.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Maximalist", "Vintage Floral", "Paste-the-Wall", "New"],
    relatedSlugs: ["limerence", "meadow-bloom"],
  },
  {
    slug: "moth-nocturne",
    name: "Moth Nocturne",
    brand: "Timorous Beasties",
    brandSlug: "timorous-beasties",
    price: 138,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    rating: 5,
    reviewCount: 56,
    description: "Timorous Beasties' moth collection by moonlight — imperial moths, luna moths, and hawk moths arranged in a dense, almost textile-like repeat on deepest charcoal. The studio's entomological precision transforms something usually overlooked into something impossible to ignore.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Botanical", "Paste-the-Wall", "Heritage"],
    relatedSlugs: ["nocturne", "glasgow-bird"],
  },
  {
    slug: "fornasetti-sol",
    name: "Fornasetti Sol",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 165,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    isBestseller: true,
    rating: 5,
    reviewCount: 203,
    description: "Cole & Son's collaboration with the Fornasetti studio produces this iconic sunface design — the Sole e Luna motif that Piero Fornasetti obsessed over for decades, now translated to wallpaper by the house that understands heritage print better than anyone. Archival and entirely of the moment.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Art Deco", "Heritage", "Paste-the-Wall", "Luxury", "Bestseller"],
    relatedSlugs: ["hummingbirds", "toile-de-verre"],
  },

  // ── Row 22 ──────────────────────────────────────────────────────
  {
    slug: "toile-de-verre",
    name: "Toile de Verre",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 168,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_D],
    rating: 5,
    reviewCount: 147,
    description: "Cole & Son's grand panoramic toile — a landscape of garden follies, pastoral idylls, and classical ruins in the tradition of 18th-century French toile de Jouy. The design's scale and detail are extraordinary: a wall-sized landscape painting printed in the toile monochrome tradition.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Grandmillennial", "Heritage", "Paste-the-Wall", "Luxury"],
    relatedSlugs: ["fornasetti-sol", "american-toile"],
  },
  {
    slug: "flamingo-pink",
    name: "Flamingo",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 155,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_B],
    isBestseller: true,
    rating: 5,
    reviewCount: 389,
    description: "Cole & Son's flamingo — one of the most photographed wallpapers in the world. A colony of flamingos stand among tropical leaves in warm pinks, greens, and gold. The design's fame hasn't dimmed its impact: some prints are simply correct, and this is one of them.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Botanical", "Paste-the-Wall", "Heritage", "Bestseller"],
    relatedSlugs: ["king-protea", "hummingbirds"],
  },
  {
    slug: "shell-bisque",
    name: "Shell Bisque",
    brand: "York Wallcoverings",
    brandSlug: "york-wallcoverings",
    price: 72,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_C],
    rating: 4,
    reviewCount: 108,
    description: "A collection of shells — conch, scallop, whelk, and periwinkle — arranged in natural, museum-specimen style on a warm bisque ground. York's coastal collection arrives at its most restrained and elegant: for beach houses that prefer natural history to nautical kitsch.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Coastal", "Paste-the-Wall"],
    relatedSlugs: ["coastal-rope", "sea-grass"],
  },
  {
    slug: "arctic-grove",
    name: "Arctic Grove",
    brand: "Rebel Walls",
    brandSlug: "rebel-walls",
    price: 78,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 5,
    reviewCount: 116,
    description: "Rebel Walls captures the birch grove in deep winter — white trunks in fresh snow, the particular silence of a Scandinavian forest after the last light has faded. The monochromatic palette and the mural scale create a room that feels like a still from a film about solitude.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "Sweden" },
    tags: ["Botanical", "Paste-the-Wall", "Mural"],
    relatedSlugs: ["woods-cole-son", "savanna-dusk"],
  },

  // ── Row 23 ──────────────────────────────────────────────────────
  {
    slug: "linen-weave",
    name: "Linen Weave",
    brand: "Graham & Brown",
    brandSlug: "graham-brown",
    price: 56,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 4,
    reviewCount: 214,
    description: "Graham & Brown's most textural design — a close-woven linen surface in warm oat and cream that adds depth to any room without committing to a pattern. The textured print works in everything from hallways to bedrooms, layering warmth without asserting itself.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "Free match", match: "Free match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Abstract", "Paste-the-Wall"],
    relatedSlugs: ["blue-linen", "grasscloth-natural"],
  },
  {
    slug: "sage-scatter",
    name: "Sage Scatter",
    brand: "Chasing Paper",
    brandSlug: "chasing-paper",
    price: 76,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    isNew: true,
    rating: 5,
    reviewCount: 59,
    description: "A loose, scattered botanical in sage green and dusty terracotta — eucalyptus leaves and wild herbs arranged with the deliberate informality that defines contemporary boho design. Chasing Paper's peel-and-stick version installs in hours and removes without damage.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Boho", "Botanical", "Peel & Stick", "New", "Renter-friendly"],
    relatedSlugs: ["desert-bloom", "fern-frond"],
  },
  {
    slug: "fern-frond",
    name: "Fern Frond",
    brand: "Tempaper",
    brandSlug: "tempaper",
    price: 64,
    priceUnit: "per roll",
    installType: "peel-and-stick",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 4,
    reviewCount: 143,
    description: "Tempaper's most botanical peel-and-stick design — large fern fronds in deep botanical green on a clean white ground. The design is straightforward and beautiful, suited to bathrooms, nurseries, and any space that wants greenery without the water requirement.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm straight match", match: "Straight match", material: "Self-adhesive vinyl", finish: "Matt", origin: "United States" },
    tags: ["Botanical", "Boho", "Peel & Stick", "Renter-friendly"],
    relatedSlugs: ["emerald-conservatory", "lily-pad-pond"],
  },
  {
    slug: "bird-and-pomegranate",
    name: "Bird & Pomegranate",
    brand: "Morris & Co.",
    brandSlug: "morris-co",
    price: 128,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 287,
    description: "Morris's Bird and Pomegranate is one of the firm's most ambitious designs — woven birds, pomegranate fruits, and foliate stems in a repeat that creates an almost tapestry-like surface. First produced in 1926 and still printed with the same fidelity to the original design.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Heritage", "Botanical", "Vintage Floral", "Paste-the-Wall", "Bestseller"],
    relatedSlugs: ["strawberry-thief", "golden-lily"],
  },

  // ── Row 24 ──────────────────────────────────────────────────────
  {
    slug: "hygge-floral",
    name: "Hygge Floral",
    brand: "Hygge & West",
    brandSlug: "hygge-west",
    price: 88,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_A],
    rating: 4,
    reviewCount: 76,
    description: "Hygge & West's cottage garden — small-scale wildflowers in a soft, naturalistic repeat on a warm cream ground. The design has the quality of pressed flowers: intimate, gentle, and suited to the spaces where you want to feel held rather than stimulated.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Cottage Core", "Vintage Floral", "Paste-the-Wall"],
    relatedSlugs: ["magnolia-peel-stick", "nordic-frost"],
  },
  {
    slug: "tangent-stripe",
    name: "Tangent Stripe",
    brand: "Harlequin",
    brandSlug: "harlequin",
    price: 95,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_D],
    rating: 4,
    reviewCount: 88,
    description: "A bold abstract stripe that plays with direction and opacity — overlapping bands of geometric colour that create the impression of movement across the wall. Harlequin's talent for making geometry feel dynamic rather than mechanical is at its best here.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "32cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Geometric", "Abstract", "Paste-the-Wall"],
    relatedSlugs: ["aurora-wave", "geo-burst"],
  },
  {
    slug: "loft-concrete",
    name: "Loft Concrete",
    brand: "Brewster",
    brandSlug: "brewster",
    price: 48,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_C],
    rating: 4,
    reviewCount: 166,
    description: "The urban concrete surface reinterpreted for residential interiors — Brewster's loft-concrete design brings the aesthetic of exposed Brutalist architecture to walls without the planning permission. The textured grey palette works in home offices, media rooms, and industrial-aesthetic spaces.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "Free match", match: "Free match", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Abstract", "Dark & Moody", "Paste-the-Wall"],
    relatedSlugs: ["boho-mudcloth", "lichen-stone"],
  },
  {
    slug: "perennial-garden",
    name: "Perennial Garden",
    brand: "Rifle Paper Co.",
    brandSlug: "rifle-paper-co",
    price: 95,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_D],
    rating: 5,
    reviewCount: 132,
    description: "Rifle Paper Co.'s perennial garden — the kind that has been tended for decades, with roses, clematis, and sweet peas that come back every year looking more settled and more beautiful. A design for rooms that want to feel like they have always been there.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "48cm half drop", match: "Half drop", material: "Non-woven substrate", finish: "Matt", origin: "United States" },
    tags: ["Cottage Core", "Vintage Floral", "Botanical", "Paste-the-Wall"],
    relatedSlugs: ["bramble-rose", "wildflower-field"],
  },

  // ── Row 25 ──────────────────────────────────────────────────────
  {
    slug: "jacobean-tree",
    name: "Jacobean Tree",
    brand: "Osborne & Little",
    brandSlug: "osborne-little",
    price: 135,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_A,
    images: [IMG_A, IMG_C],
    rating: 5,
    reviewCount: 97,
    description: "The Jacobean tree of life — one of the oldest motifs in English embroidery — reinterpreted by Osborne & Little with a modern understanding of scale and weight. Flowering branches emerge from a curling root structure in a design that contains centuries of decorative ambition.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Heritage", "Botanical", "Grandmillennial", "Paste-the-Wall"],
    relatedSlugs: ["regency-damask", "folly-brook"],
  },
  {
    slug: "toile-countryside",
    name: "Toile Countryside",
    brand: "Sanderson",
    brandSlug: "sanderson",
    price: 108,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_B,
    images: [IMG_B, IMG_A],
    rating: 5,
    reviewCount: 163,
    description: "Sanderson's panoramic countryside toile — English pastoral scenes rendered in traditional single-colour monochrome in the tradition of French toile de Jouy. The grandmillennial revival has given this design a new and enthusiastic audience, but it never actually went away.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "53cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Grandmillennial", "Heritage", "Paste-the-Wall"],
    relatedSlugs: ["american-toile", "etchings-seas"],
  },
  {
    slug: "zebra-dusk",
    name: "Zebra Dusk",
    brand: "Cole & Son",
    brandSlug: "cole-son",
    price: 162,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_C,
    images: [IMG_C, IMG_A],
    rating: 5,
    reviewCount: 174,
    description: "Cole & Son's zebra from their Natural History collection — against a ground of deep dusk blue. The graphic precision of the zebra stripe against the moody background creates a design that sits between safari drama and high-fashion cool, suited to any room that wants an unmistakable position.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "64cm straight match", match: "Straight match", material: "Non-woven substrate", finish: "Matt", origin: "United Kingdom" },
    tags: ["Dark & Moody", "Heritage", "Paste-the-Wall", "Luxury"],
    relatedSlugs: ["flamingo-pink", "woods-cole-son"],
  },
  {
    slug: "deco-terrazzo",
    name: "Deco Terrazzo",
    brand: "Fromental",
    brandSlug: "fromental",
    price: 172,
    priceUnit: "per roll",
    installType: "paste-the-wall",
    imageUrl: IMG_D,
    images: [IMG_D, IMG_B],
    isNew: true,
    rating: 5,
    reviewCount: 29,
    description: "Fromental's Art Deco take on terrazzo — the ancient Venetian floor surface reimagined as a luxury wall covering. Chips of jade, marble, and onyx appear to float in a ground of warm ivory, creating a surface that is simultaneously historical and entirely contemporary.",
    details: { rollWidth: "52cm (20.5 in)", rollLength: "10m (32.8 ft)", patternRepeat: "Free match", match: "Free match", material: "Non-woven substrate", finish: "Satin", origin: "United Kingdom" },
    tags: ["Art Deco", "Abstract", "Paste-the-Wall", "Heritage", "Luxury", "New"],
    relatedSlugs: ["art-deco-soleil", "deco-lattice"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string): Product[] {
  const product = getProduct(slug);
  if (!product) return [];
  return product.relatedSlugs.map((s) => getProduct(s)).filter(Boolean) as Product[];
}
