// Dominant colour(s) per product — drives the colour filter on /products.
// Up to 2 colours per product; first is primary.
export const PRODUCT_COLORS: Record<string, string[]> = {
  // Row 1-5
  "verdant-canopy":       ["Green"],
  "emerald-conservatory": ["Green"],
  "midnight-garden":      ["Dark", "Green"],
  "hex-noir":             ["Dark"],
  "archive-rose":         ["Pink", "Neutral"],
  "woods-cole-son":       ["Neutral", "Dark"],
  "momentum-grid":        ["Neutral"],
  "papilio-botanical":    ["Green", "Multi"],
  "blackthorn":           ["Dark", "Green"],
  "diamond-lattice":      ["Neutral"],
  "hummingbirds":         ["Multi", "Green"],
  "garden-party":         ["Multi", "Pink"],
  "imperial-garden":      ["Multi", "Green"],
  "magnolia-peel-stick":  ["Pink", "Neutral"],
  "strawberry-thief":     ["Blue", "Multi"],
  "nocturne":             ["Dark", "Green"],
  "verdure":              ["Green"],
  "meadow-bloom":         ["Multi", "Green"],
  "velvet-forest":        ["Dark", "Green"],
  "art-deco-soleil":      ["Dark", "Gold"],
  // Row 6-10
  "jungle-reverie":       ["Green"],
  "chevron-slate":        ["Neutral", "Dark"],
  "terracotta-wave":      ["Neutral"],
  "coral-reef":           ["Blue", "Multi"],
  "peony-garden":         ["Pink"],
  "willow-bough":         ["Green"],
  "fjord-fog":            ["Blue", "Neutral"],
  "aurora-wave":          ["Green", "Blue"],
  "coastal-rope":         ["Blue", "Neutral"],
  "king-protea":          ["Multi", "Neutral"],
  "coastal-stripe":       ["Blue", "White"],
  "wildflower-field":     ["Multi"],
  "folly-brook":          ["Green", "Blue"],
  "limerence":            ["Multi", "Green"],
  "thistle-dark":         ["Dark", "Multi"],
  "shou-lao":             ["Multi", "Blue"],
  "chevron-gold":         ["Gold", "Dark"],
  "savanna-dusk":         ["Neutral"],
  "arch-shadow":          ["Neutral"],
  "desert-bloom":         ["Neutral", "Multi"],
  // Row 11-15
  "sunburst-retro":       ["Gold", "Neutral"],
  "bluebell-wood":        ["Blue"],
  "chrysanthemum-blue":   ["Blue"],
  "pine-needle":          ["Green", "White"],
  "geo-burst":            ["Multi"],
  "blue-linen":           ["Blue"],
  "shiplap-white":        ["White"],
  "strawberry-fields":    ["Multi", "Pink"],
  "sea-grass":            ["Green", "Neutral"],
  "palmeral":             ["Green", "Dark"],
  "glasgow-bird":         ["Dark"],
  "edo-birds":            ["Blue", "Multi"],
  "broadway-noir":        ["Dark", "Gold"],
  "palm-paradise":        ["Green"],
  "mosaic-blush":         ["Pink", "Neutral"],
  "sunset-stripe":        ["Multi", "Neutral"],
  "grasscloth-natural":   ["Neutral"],
  "honeysuckle-trellis":  ["Multi", "Green"],
  "acanthus-scroll":      ["Green", "Gold"],
  "noma-grid":            ["White", "Neutral"],
  // Row 16-20
  "tropical-luxe":        ["Green", "Dark"],
  "farmhouse-bloom":      ["Multi", "Neutral"],
  "daisy-meadow":         ["Multi", "White"],
  "bramble-rose":         ["Pink", "Green"],
  "peacock-manor":        ["Blue", "Gold"],
  "wilderness-emerald":   ["Green", "Dark"],
  "lichen-stone":         ["Neutral", "Dark"],
  "moonlit-garden":       ["Dark", "Blue"],
  "deco-lattice":         ["Dark", "Gold"],
  "rainforest-floor":     ["Green"],
  "stripe-dusk":          ["Neutral"],
  "indigo-lattice":       ["Blue", "White"],
  "lily-pad-pond":        ["Blue", "Green"],
  "etchings-seas":        ["Blue", "Neutral"],
  "golden-lily":          ["Gold", "Green"],
  "nordic-frost":         ["Blue", "White"],
  "monstera-shadow":      ["Dark", "Green"],
  "american-toile":       ["Blue", "Neutral"],
  "boho-mudcloth":        ["Neutral", "Dark"],
  "canopy-illustrated":   ["Green", "Multi"],
  // Row 21-25
  "regency-damask":       ["Neutral", "Gold"],
  "fruit-folly":          ["Multi"],
  "moth-nocturne":        ["Dark"],
  "fornasetti-sol":       ["Neutral", "Gold"],
  "toile-de-verre":       ["Blue", "Neutral"],
  "flamingo-pink":        ["Pink", "Multi"],
  "shell-bisque":         ["Neutral"],
  "arctic-grove":         ["White", "Neutral"],
  "linen-weave":          ["Neutral"],
  "sage-scatter":         ["Green", "Neutral"],
  "fern-frond":           ["Green", "White"],
  "bird-and-pomegranate": ["Multi", "Green"],
  "hygge-floral":         ["Multi", "Pink"],
  "tangent-stripe":       ["Multi"],
  "loft-concrete":        ["Neutral", "Dark"],
  "perennial-garden":     ["Multi", "Pink"],
  "jacobean-tree":        ["Green", "Multi"],
  "toile-countryside":    ["Blue", "Neutral"],
  "zebra-dusk":           ["Dark", "Blue"],
  "deco-terrazzo":        ["Neutral", "Multi"],
};

export const COLOUR_FILTERS = [
  "All colours",
  "Green",
  "Blue",
  "Dark",
  "Neutral",
  "Pink",
  "Gold",
  "Multi",
  "White",
];
