import { PRODUCT_COLORS } from "./productColors";

// Maps primary colour family → CSS filter applied to the base product image.
// All products currently share one of 4 base photos; filters create visual variety.
const COLOR_FILTER: Record<string, string> = {
  Green:   "none",
  Dark:    "brightness(0.58) contrast(1.25) saturate(0.8)",
  Blue:    "hue-rotate(195deg) saturate(1.15) brightness(0.9)",
  Pink:    "hue-rotate(308deg) saturate(1.9) brightness(1.05)",
  Gold:    "sepia(0.8) saturate(2.2) hue-rotate(8deg) brightness(1.08)",
  Neutral: "sepia(0.45) saturate(0.45) brightness(1.2)",
  Multi:   "saturate(1.55) contrast(1.08)",
  White:   "grayscale(1) brightness(1.8) contrast(0.6)",
};

// Per-slug overrides where the primary colour doesn't capture the full character.
const SLUG_OVERRIDE: Record<string, string> = {
  "sea-grass":          "sepia(0.35) saturate(1.2) hue-rotate(20deg) brightness(1.05)",
  "terracotta-wave":    "sepia(0.9) saturate(2.0) hue-rotate(340deg) brightness(0.95)",
  "midnight-garden":    "brightness(0.55) contrast(1.3) saturate(0.85) hue-rotate(210deg)",
  "moonlit-garden":     "brightness(0.6) contrast(1.2) hue-rotate(230deg) saturate(0.9)",
  "broadway-noir":      "brightness(0.5) contrast(1.4) sepia(0.4) hue-rotate(30deg)",
  "art-deco-soleil":    "sepia(0.7) saturate(2.0) hue-rotate(20deg) brightness(0.85)",
  "golden-lily":        "sepia(0.6) saturate(2.5) hue-rotate(15deg) brightness(1.1)",
  "acanthus-scroll":    "sepia(0.5) saturate(2.0) hue-rotate(10deg)",
  "chevron-gold":       "sepia(0.8) saturate(2.0) hue-rotate(5deg) brightness(1.0)",
  "fjord-fog":          "hue-rotate(185deg) saturate(0.7) brightness(1.1)",
  "bluebell-wood":      "hue-rotate(220deg) saturate(1.3) brightness(0.85)",
  "loft-concrete":      "grayscale(0.8) brightness(0.85) contrast(1.1)",
  "savanna-dusk":       "sepia(0.6) saturate(1.0) hue-rotate(20deg) brightness(1.05)",
  "arch-shadow":        "grayscale(0.5) brightness(0.8) contrast(1.15)",
  "shiplap-white":      "grayscale(0.9) brightness(1.9) contrast(0.5)",
  "noma-grid":          "grayscale(0.7) brightness(1.5) contrast(0.75)",
  "arctic-grove":       "hue-rotate(165deg) saturate(0.3) brightness(1.4)",
  "nordic-frost":       "hue-rotate(185deg) saturate(0.6) brightness(1.2)",
  "flamingo-pink":      "hue-rotate(315deg) saturate(2.2) brightness(1.1)",
  "flamingo":           "hue-rotate(315deg) saturate(2.2) brightness(1.1)",
  "bramble-rose":       "hue-rotate(310deg) saturate(1.6) brightness(1.0)",
  "peacock-manor":      "hue-rotate(175deg) saturate(1.4) brightness(0.85)",
  "indigo-lattice":     "hue-rotate(230deg) saturate(1.5) brightness(0.8)",
  "shou-lao":           "hue-rotate(10deg) saturate(1.5) brightness(0.9)",
  "palmeral":           "brightness(0.72) saturate(1.3) hue-rotate(145deg)",
  "tropical-luxe":      "brightness(0.75) saturate(1.4) hue-rotate(155deg)",
  "wilderness-emerald": "hue-rotate(140deg) brightness(0.75) saturate(1.5)",
  "lichen-stone":       "sepia(0.3) saturate(0.35) brightness(0.9) contrast(1.1)",
  "grasscloth-natural": "sepia(0.6) saturate(0.5) brightness(1.1)",
  "linen-weave":        "sepia(0.5) saturate(0.4) brightness(1.2)",
  "boho-mudcloth":      "sepia(0.7) saturate(0.8) brightness(0.9)",
  "desert-bloom":       "sepia(0.5) saturate(1.4) hue-rotate(330deg) brightness(1.05)",
  "king-protea":        "hue-rotate(5deg) saturate(1.6) brightness(1.0)",
  "shell-bisque":       "sepia(0.55) saturate(0.5) brightness(1.25) hue-rotate(5deg)",
  "blue-linen":         "hue-rotate(195deg) saturate(0.9) brightness(1.1) sepia(0.1)",
  "strawberry-thief":   "hue-rotate(200deg) saturate(1.3) brightness(0.9)",
  "coral-reef":         "hue-rotate(175deg) saturate(1.2) brightness(0.9)",
  "coastal-rope":       "hue-rotate(180deg) saturate(0.7) brightness(1.05)",
  "coastal-stripe":     "hue-rotate(185deg) saturate(0.8) brightness(1.1)",
  "lily-pad-pond":      "hue-rotate(165deg) saturate(1.1) brightness(0.95)",
  "folly-brook":        "hue-rotate(170deg) saturate(0.9) brightness(1.0)",
  "aurora-wave":        "hue-rotate(160deg) saturate(1.2) brightness(0.9)",
  "etchings-seas":      "hue-rotate(190deg) saturate(0.75) brightness(1.05)",
  "american-toile":     "hue-rotate(200deg) saturate(0.85) brightness(1.0)",
  "toile-countryside":  "hue-rotate(205deg) saturate(0.75) brightness(1.08)",
  "toile-de-verre":     "hue-rotate(195deg) saturate(0.8) brightness(1.05)",
  "deco-lattice":       "sepia(0.6) saturate(1.8) hue-rotate(15deg) brightness(0.8)",
  "fornasetti-sol":     "sepia(0.7) saturate(1.6) hue-rotate(10deg) brightness(1.05)",
  "regency-damask":     "sepia(0.5) saturate(0.8) brightness(1.1) hue-rotate(10deg)",
  "sunburst-retro":     "sepia(0.7) saturate(2.0) hue-rotate(15deg) brightness(1.05)",
  "deco-terrazzo":      "sepia(0.25) saturate(1.1) brightness(1.1)",
  "tangent-stripe":     "saturate(1.7) hue-rotate(330deg) brightness(0.95)",
  "sunset-stripe":      "sepia(0.5) saturate(1.8) hue-rotate(350deg) brightness(1.0)",
  "fruit-folly":        "hue-rotate(15deg) saturate(1.8) brightness(1.05)",
  "garden-party":       "hue-rotate(320deg) saturate(1.5) brightness(1.05)",
  "hummingbirds":       "hue-rotate(30deg) saturate(1.5) brightness(1.0)",
  "wildflower-field":   "hue-rotate(25deg) saturate(1.6) brightness(1.05)",
  "meadow-bloom":       "hue-rotate(15deg) saturate(1.5) brightness(1.05)",
  "perennial-garden":   "hue-rotate(320deg) saturate(1.4) brightness(1.05)",
  "hygge-floral":       "hue-rotate(330deg) saturate(1.5) brightness(1.05)",
  "daisy-meadow":       "hue-rotate(30deg) saturate(1.3) brightness(1.1)",
  "farmhouse-bloom":    "hue-rotate(10deg) saturate(1.4) brightness(1.05)",
  "zebra-dusk":         "grayscale(0.5) brightness(0.65) contrast(1.3)",
  "limerence":          "hue-rotate(120deg) saturate(1.6) brightness(0.9)",
  "mosaic-blush":       "hue-rotate(315deg) saturate(1.5) brightness(1.1)",
  "peony-garden":       "hue-rotate(310deg) saturate(2.0) brightness(1.05)",
  "archive-rose":       "hue-rotate(310deg) saturate(1.7) brightness(1.05)",
  "magnolia-peel-stick":"hue-rotate(315deg) saturate(1.3) brightness(1.1)",
  "blackthorn":         "brightness(0.65) contrast(1.2) saturate(0.7)",
  "velvet-forest":      "brightness(0.62) saturate(1.1) hue-rotate(145deg)",
  "thistle-dark":       "brightness(0.65) contrast(1.15) hue-rotate(280deg) saturate(1.2)",
  "glasgow-bird":       "brightness(0.6) contrast(1.2) hue-rotate(200deg) saturate(1.0)",
  "moth-nocturne":      "brightness(0.5) contrast(1.35) saturate(0.6)",
  "monstera-shadow":    "brightness(0.63) saturate(1.2) hue-rotate(145deg)",
  "pine-needle":        "hue-rotate(110deg) saturate(0.8) brightness(1.05)",
  "sage-scatter":       "hue-rotate(85deg) saturate(0.8) brightness(1.1)",
  "fern-frond":         "hue-rotate(95deg) saturate(0.9) brightness(1.05)",
  "canopy-illustrated": "hue-rotate(30deg) saturate(1.2) brightness(0.95)",
  "jacobean-tree":      "hue-rotate(20deg) saturate(1.3) brightness(0.9)",
  "bird-and-pomegranate":"hue-rotate(350deg) saturate(1.5) brightness(1.0)",
  "edo-birds":          "hue-rotate(195deg) saturate(1.2) brightness(0.9)",
  "rainforest-floor":   "hue-rotate(140deg) saturate(1.3) brightness(0.8)",
  "palm-paradise":      "hue-rotate(135deg) saturate(1.4) brightness(0.85)",
  "jungle-reverie":     "hue-rotate(150deg) saturate(1.3) brightness(0.85)",
  "willow-bough":       "hue-rotate(80deg) saturate(1.0) brightness(1.05)",
  "verdure":            "hue-rotate(50deg) saturate(0.9) brightness(1.0)",
  "papilio-botanical":  "hue-rotate(40deg) saturate(1.3) brightness(0.98)",
  "imperial-garden":    "hue-rotate(20deg) saturate(1.4) brightness(0.95)",
  "geo-burst":          "saturate(1.8) contrast(1.1) hue-rotate(30deg)",
  "chrysanthemum-blue": "hue-rotate(200deg) saturate(1.4) brightness(0.88)",
  "shou-lao":           "hue-rotate(10deg) saturate(1.5)",
  "strawberry-fields":  "hue-rotate(340deg) saturate(1.6) brightness(1.05)",
  "honeysuckle-trellis":"hue-rotate(30deg) saturate(1.5) brightness(1.0)",
};

export function getProductImageFilter(slug: string): string {
  if (SLUG_OVERRIDE[slug]) return SLUG_OVERRIDE[slug];
  const colors = PRODUCT_COLORS[slug];
  if (!colors || colors.length === 0) return "none";
  return COLOR_FILTER[colors[0]] ?? "none";
}
